[package]
name = "yabe"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "yabe"
path = "src/main.rs"

[lib]
name = "yabe"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
yaml-rust2 = "0.8.1"
